# Generated by Django 5.2.7 on 2025-10-19 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('motivo_consulta', models.TextField()),
                ('diagnostico_principal', models.TextField()),
                ('tratamiento', models.TextField()),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Historia Clínica',
                'verbose_name_plural': 'Historias Clínicas',
                'ordering': ['-fecha_consulta'],
            },
        ),
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('siglas', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Obra Social',
                'verbose_name_plural': 'Obras Sociales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Profesionales',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ExamenOftalmologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agudeza_visual_od', models.CharField(blank=True, max_length=50, verbose_name='AV OD')),
                ('agudeza_visual_oi', models.CharField(blank=True, max_length=50, verbose_name='AV OI')),
                ('biomicroscopia', models.TextField(blank=True)),
                ('fondo_ojo', models.TextField(blank=True, verbose_name='Fondo de Ojo')),
                ('presion_intraocular_od', models.CharField(blank=True, max_length=20, verbose_name='PIO OD')),
                ('presion_intraocular_oi', models.CharField(blank=True, max_length=20, verbose_name='PIO OI')),
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examen', to='gestion_clinica.historiaclinica')),
            ],
            options={
                'verbose_name': 'Examen Oftalmológico',
                'verbose_name_plural': 'Exámenes Oftalmológicos',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_registro', models.CharField(blank=True, editable=False, max_length=6, null=True, unique=True, verbose_name='Número de Registro')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('telefono', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=255)),
                ('num_afiliado', models.CharField(blank=True, max_length=50, null=True)),
                ('antecedentes_sistemicos', models.TextField(blank=True, verbose_name='Antecedentes Sistémicos')),
                ('obra_social', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_clinica.obrasocial')),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias_clinicas', to='gestion_clinica.paciente'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_clinica.profesional'),
        ),
    ]
