# Generated by Django 5.2.7 on 2025-10-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Se ha corregido la dependencia para apuntar al archivo anterior válido (0002)
        # ya que la migración 0003_prescripcionlentes fue eliminada.
        ('gestion_clinica', '0002_alter_historiaclinica_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenoftalmologico',
            name='fecha_anulacion',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='Fecha de Anulación'),
        ),
        migrations.AddField(
            model_name='examenoftalmologico',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='antecedentes_oftalmologicos',
            field=models.TextField(
                blank=True, verbose_name='Antecedentes Oftalmológicos'),
        ),
    ]
