# Generated by Django 5.2.7 on 2025-10-27 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0004_examenoftalmologico_fecha_anulacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examenoftalmologico',
            name='fecha_anulacion',
        ),
        migrations.RemoveField(
            model_name='examenoftalmologico',
            name='is_active',
        ),
    ]
