# Generated by Django 5.2.7 on 2025-10-20 22:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historiaclinica',
            options={'ordering': ['-fecha'], 'verbose_name': 'Historia Clínica', 'verbose_name_plural': 'Historias Clínicas'},
        ),
        migrations.RenameField(
            model_name='examenoftalmologico',
            old_name='presion_intraocular_od',
            new_name='pio_od',
        ),
        migrations.RenameField(
            model_name='examenoftalmologico',
            old_name='presion_intraocular_oi',
            new_name='pio_oi',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='diagnostico_principal',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='fecha_consulta',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='direccion',
        ),
        migrations.AddField(
            model_name='examenoftalmologico',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones del Examen'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='diagnostico',
            field=models.TextField(default='Diagnóstico no especificado', verbose_name='Diagnóstico Principal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 00:00:00', verbose_name='Fecha de Consulta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='domicilio',
            field=models.CharField(default='Domicilio no registrado', max_length=255, verbose_name='Domicilio'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('ATENDIDO', 'Atendido'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=10)),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones del Turno')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='gestion_clinica.paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos_asignados', to='gestion_clinica.profesional')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['fecha_hora'],
            },
        ),
    ]
